name: ci

on:
  push:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Install system dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y enchant-2 pandoc
          sudo apt install -y \
            dvipng \
            dvisvgm \
            fonts-freefont-otf \
            imagemagick \
            latexmk \
            tex-gyre \
            texlive-fonts-extra \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-latex-recommended \
            texlive-plain-generic

      - name: Install python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: HTML
        run: |
          python3 -m sphinx -W --nitpicky -b html . _build/html
        working-directory: adpm

      - name: PDF
        run: |
          python3 -m sphinx -M latexpdf . _build -W --nitpicky
        working-directory: adpm

      - name: Check links
        run: |
          python3 -m sphinx -W --nitpicky -b linkcheck . _build/linkcheck
        working-directory: adpm

      - name: Spellcheck
        run: |
          python3 -m sphinx -W --nitpicky -b spelling . _build/spelling
        working-directory: adpm

      - name: PDF Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: pdf
          archive: false
          path: |
            adpm/_build/latex/adpm.pdf
      - name: HTML Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: html
          path: |
            adpm/_build/html/

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Pre-commit
        uses: pre-commit/action@v3.0.1

  conda:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v7

      - uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: latest
          environment-file: environment.yml
          activate-environment: adpm

      - name: HTML
        run: |
          mamba run -n adpm make SPHINXBUILD="python3 -m sphinx" html

  dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Install python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: dist
        run: |
          python3 -m build --sdist

      - name: twine
        run: |
          python3 -m twine check dist/*.tar.gz

      - name: Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: sdist
          archive: false
          path: |
            dist/*.tar.gz
